### ISSUE TITLE
Cropping causes black corners

### ISSUE THREAD

**Issue by RossLote** [MattKetmo/darkroomjs#44] opened 2015-04-02 15:48 UTC
![thwaites-triple_c2-thumb_odbavnv](https://cloud.githubusercontent.com/assets/1877650/6967566/0943ae9c-d958-11e4-9ca4-a7a26ee05b1d.jpg)

**Comment by bazjapan** [comment] 2015-05-13 08:47
was just about to take a look at this myself.  I suspect the cropCurrentZone method needs a tweak - maybe hide the handles before calling canvas.toDataURL.
Did you have any luck?

**Comment by ericfreese** [comment] 2015-05-13 18:34
It looks to me like this is caused by [this line](https://github.com/RossLote/darkroomjs/blob/master/lib/js/plugins/darkroom.crop.js#L416) not causing the canvas to re-render. The line ought to be removed and replaced with `this.cropZone.remove();` no?

**Comment by sathio** [comment] 2015-05-14 16:36
@ericfreese yes, this fixes it for me

**Comment by RossLote** [comment] 2015-05-15 07:05
@ericfreese  Yeah, that was my fix too.

**Comment by MattKetmo** [comment] 2015-08-01 15:57
This should be fixed with version 2.0.0

**Closed by MattKetmo** 2015-08-01 15:57 UTC
